### ISSUE TITLE
Refresh rate changes will hang external MIDI devices

### ISSUE THREAD

**Issue by realnc** [libretro/dosbox-svn#10]
I'm not sure if this fixable at all, because a refresh rate change needs to change environment with the `RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO` flag, which is very expensive.

The issue with this is that games that utilize two resolutions and switch between them will hang external MIDI modules like the MT-32 or Roland Sound Canvas (either real devices or emulated ones like Munt or SCVA.) This also happens when exiting the game, in which case you'll get indefinitely hanging notes.

**Comment by fr500** [comment]
This should be fixed in RetroArch and not in the core.
The SET_AV_INFO switching behavior is controlled by that.

Ideally MIDI shouldn't need to be reinitialized at all for this but I think RA just reinits everything.

**Comment by fr500** [comment]
On a sidenote, I plan to do a ECE style core (may call it differently since it wouldn't be identical to ECE) and that would include fluydsynth which would alleviate the problem somewhat.

**Comment by realnc** [comment]
What are the implications of not doing a `RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO`? I changed the code as follows, and I still get pixel-perfect sync but without the annoying video reinit:

```diff
diff --git a/libretro/libretro.cpp b/libretro/libretro.cpp
index c920cd0a..17cf0b1f 100644
--- a/libretro/libretro.cpp
+++ b/libretro/libretro.cpp
@@ -1362,23 +1362,20 @@ void retro_run (void)
         {
             new_av_info.timing.fps = render.src.fps;
             new_av_info.timing.sample_rate = (double)MIXER_RETRO_GetFrequency();
+            currentFPS = render.src.fps;
 
-            environ_cb(RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO , &new_av_info);
             if (log_cb)
                 log_cb(RETRO_LOG_INFO,"[dosbox] refresh rate changed %f => %f\n", currentFPS, render.src.fps);
-
-            currentFPS = render.src.fps;
         }
-        else
-        {
-            environ_cb(RETRO_ENVIRONMENT_SET_GEOMETRY, &new_av_info);
-            if (log_cb)
-                log_cb(RETRO_LOG_INFO,"[dosbox] resolution changed %dx%d => %dx%d\n",
-                    currentWidth, currentHeight, RDOSGFXwidth, RDOSGFXheight);
 
-            currentWidth = RDOSGFXwidth;
-            currentHeight = RDOSGFXheight;
-        }
+        environ_cb(RETRO_ENVIRONMENT_SET_GEOMETRY, &new_av_info);
+        if (log_cb)
+            log_cb(RETRO_LOG_INFO,"[dosbox] resolution changed %dx%d => %dx%d\n",
+                   currentWidth, currentHeight, RDOSGFXwidth, RDOSGFXheight);
+
+        currentWidth = RDOSGFXwidth;
+        currentHeight = RDOSGFXheight;
+
     }
 
     bool updated = false;
```

**Comment by fr500** [comment]
It shouldn't work, GEOMETRY as the name implies changes... GEOMETRY if it works it's probably a RA bug, I'm just following the SPEC.

**Comment by fr500** [comment]
```C
#define RETRO_ENVIRONMENT_SET_GEOMETRY 37
                                           /* const struct retro_game_geometry * --
                                            * This environment call is similar to SET_SYSTEM_AV_INFO for changing
                                            * video parameters, but provides a guarantee that drivers will not be
                                            * reinitialized.
                                            * This can only be called from within retro_run().
                                            *
                                            * The purpose of this call is to allow a core to alter nominal
                                            * width/heights as well as aspect ratios on-the-fly, which can be
                                            * useful for some emulators to change in run-time.
                                            *
                                            * max_width/max_height arguments are ignored and cannot be changed
                                            * with this call as this could potentially require a reinitialization or a
                                            * non-constant time operation.
                                            * If max_width/max_height are to be changed, SET_SYSTEM_AV_INFO is required.
                                            *
                                            * A frontend must guarantee that this environment call completes in
                                            * constant time.
                                            */
```

**Comment by realnc** [comment]
Yes, it seems like a bug. I had disabled the "sync to exact content framerate" option in RA, and (weirdly) this results in perfect sync with the above patch. Enabling that option breaks sync and timing.

It's a pretty awesome bug though, I must say. I'll be using it personally since it fixes the problem completely :grin:

**Comment by fr500** [comment]
@twinaphex any words on this.
It actually works. You can change refresh rate without re initializing everything, so what's the point of AV_INFO other than changing the resampler rate?

Bug, or should it grant a change in the spec?

**Comment by fr500** [comment]
On a second thought... it shouldn't change the spec... a bug in one frontend shouldn't mean the spect should be rewritten. Also it may work on one driver or platform and not in another

Bug should be fixed but.. if it works on all drivers maybe the SET_AV_INFO env should be reimplemented in RA to not reinit unless really neccesary. I figure the only really necessary use cases would be to increase MAX_WIDTH/HEIGHT and/or change resampler rate.

**Comment by fr500** [comment]
@realnc does the FPS counter reflect the change with your patch? can't test right now.
IE: is it working at 70 or whatever it switches to?

**Comment by realnc** [comment]
Yes, the FPS counter shows the correct value when the game switches to a different refresh.

**Comment by fr500** [comment]
MIDI generally hangs on AV_INFO changes, or on exit, that's a RA issue, I feel like the underlying issue here is solved

**Comment by realnc** [comment]
I would like to keep this bug open though, and close it when/if RA or libretro change or add an API to do an AV_INFO change without driver re-init. For as long as this doesn't happen, it's going to be an issue for this core. It's not just MIDI. It's also the screen flashing and digital sound is also freezing for the duration of the switch.

**Comment by realnc** [comment]
This was merged:

https://github.com/libretro/RetroArch/pull/9715

So we can finally close this one!
